# Autograd

In [1]:
import torch

In [2]:
x = torch.ones(2,2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
print(y.grad_fn)

In [5]:
z = y*y*3
print(z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)


In [6]:
out = z.mean()
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [7]:
out.backward()

In [8]:
print(x.grad) # d(out)/dx

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [9]:
a = torch.randn(2,2)
print(a)

tensor([[ 0.4408, -0.6931],
        [ 1.1380,  2.0854]])


In [11]:
a = ((a*3)/ (a-1))
print(a)

tensor([[-2.3647,  1.2281],
        [24.7342,  5.7639]])


In [12]:
print(a.requires_grad)

False


In [13]:
a.requires_grad_(True)

tensor([[-2.3647,  1.2281],
        [24.7342,  5.7639]], requires_grad=True)

In [14]:
b = (a*a).sum()
print(b)

tensor(652.1051, grad_fn=<SumBackward0>)


In [16]:
print(a.requires_grad)

True


In [20]:
x = torch.randn(3, requires_grad = True)
y = x*2
while y.data.norm() < 1000:
    y= y*2
print(y)

tensor([  458.9685,  -521.7260, -1097.1267], grad_fn=<MulBackward0>)


In [21]:
v= torch.tensor([0.1, 1.0, 0.0001], dtype= torch.float)
print(v)

tensor([1.0000e-01, 1.0000e+00, 1.0000e-04])


In [22]:
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [23]:
print(x.requires_grad)

True


In [25]:
with torch.no_grad():
    print((x**2).requires_grad)

False


In [26]:
print(x.requires_grad)

True


In [27]:
y = x.detach()
print(y.requires_grad)

False
