In [1]:
import csv
import torch
import numpy as np

In [2]:
wine_path = "C:\\Users\\amirs\\Downloads\\data\\winedata.csv"

In [3]:
# Print path
print(wine_path)

C:\Users\amirs\Downloads\data\winedata.csv


In [4]:
# Load the dataset
wine_numpy = np.loadtxt(wine_path, dtype = np.float32, delimiter=";", skiprows=1)

In [5]:
# Convert NumPy array to a PyTorch tensor
wine_tensor = torch.from_numpy(wine_numpy)

In [6]:
# Indep variables
data = wine_tensor[:, :-1]

In [7]:
# Target variable
target = wine_tensor[:, -1].long()

In [8]:
target.shape

torch.Size([4898])

In [9]:
target.dim()

1

In [10]:
print(target)

tensor([6, 6, 6,  ..., 6, 7, 6])


In [11]:
target.unique()

tensor([3, 4, 5, 6, 7, 8, 9])

In [12]:
target.shape[0]

4898

In [13]:
target_onehot = torch.zeros(target.shape[0], 10)

In [14]:
target_onehot.shape

torch.Size([4898, 10])

In [15]:
target_onehot.unique()

tensor([0.])

In [16]:
print(target_onehot)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [17]:
target_onehot.dim()

2

In [20]:
a= target_onehot.scatter_(1, target.unsqueeze(1), 1.0)

In [21]:
print(a)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [22]:
a.unique()

tensor([0., 1.])

In [19]:
target_unsqueezed = target.unsqueeze(1)
target_unsqueezed

tensor([[6],
        [6],
        [6],
        ...,
        [6],
        [7],
        [6]])

# Normalize data

In [46]:
data = wine_tensor[:, :-1]

In [27]:
print(data)

tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
        [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
        [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
        ...,
        [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
        [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
        [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]])


In [25]:
data.dim()

2

In [40]:
data.shape[0]

4898

In [32]:
data.shape[1]

11

In [44]:
data_mean = torch.mean(data, dim=0)

In [42]:
print(data_mean)

tensor([23.3296, 15.3521, 14.3205,  ..., 14.8194, 14.0655, 13.0709])


In [35]:
data_var = torch.var(data, dim=0)

In [36]:
print(data_var)

tensor([7.1211e-01, 1.0160e-02, 1.4646e-02, 2.5726e+01, 4.7733e-04, 2.8924e+02,
        1.8061e+03, 8.9455e-06, 2.2801e-02, 1.3025e-02, 1.5144e+00])


In [37]:
data_mean = torch.mean(data, dim=1)

In [45]:
# Normalize data by subtracting the mean and dividing by the standard deviation
data_normalized = (data - data_mean) / torch.sqrt(data_var)
data_normalized

tensor([[ 1.7209e-01, -8.1764e-02,  2.1325e-01,  ..., -1.2468e+00,
         -3.4914e-01, -1.3930e+00],
        [-6.5743e-01,  2.1587e-01,  4.7991e-02,  ...,  7.3992e-01,
          1.3467e-03, -8.2418e-01],
        [ 1.4756e+00,  1.7448e-02,  5.4378e-01,  ...,  4.7502e-01,
         -4.3677e-01, -3.3662e-01],
        ...,
        [-4.2042e-01, -3.7940e-01, -1.1915e+00,  ..., -1.3131e+00,
         -2.6152e-01, -9.0544e-01],
        [-1.6054e+00,  1.1666e-01, -2.8253e-01,  ...,  1.0048e+00,
         -9.6250e-01,  1.8574e+00],
        [-1.0129e+00, -6.7703e-01,  3.7852e-01,  ...,  4.7502e-01,
         -1.4882e+00,  1.0448e+00]])