# Data Type

In [1]:
import torch

In [2]:
float_tensor = torch.ones(5, dtype= torch.float)
print(float_tensor)

tensor([1., 1., 1., 1., 1.])


In [3]:
float_tensor.dtype

torch.float32

In [4]:
float_tensor.device

device(type='cpu')

In [5]:
float_tensor.layout

torch.strided

In [6]:
float_tensor.size()

torch.Size([5])

In [7]:
float_tensor.dim()

1

In [8]:
double_tensor = torch.ones(1, dtype= torch.double)
print(double_tensor)

tensor([1.], dtype=torch.float64)


In [9]:
complex_float = torch.ones(1, dtype= torch.complex64)
print(complex_float)

tensor([1.+0.j])


In [10]:
complex_double = torch.ones(1, dtype = torch.complex128)
print(complex_double)

tensor([1.+0.j], dtype=torch.complex128)


In [11]:
int_tensor = torch.ones(1, dtype= torch.int)
print(int_tensor)

tensor([1], dtype=torch.int32)


In [12]:
long_tensor = torch.ones(5, dtype= torch.long)
print(long_tensor)

tensor([1, 1, 1, 1, 1])


In [13]:
long_tensor.dtype

torch.int64

In [16]:
unit_tensor = torch.ones(2, dtype = torch.uint8)
print(unit_tensor)

tensor([1, 1], dtype=torch.uint8)


In [17]:
bool_tensor = torch.ones(5, dtype= torch.bool)
print(bool_tensor)

tensor([True, True, True, True, True])


In [18]:
bool_tensor.dtype

torch.bool

In [19]:
bool_tensor.dim()

1

In [20]:
long_zerodim = torch.tensor(5, dtype= torch.long)
print(long_zerodim)

tensor(5)


In [21]:
long_zerodim.dtype

torch.int64

In [22]:
long_zerodim.dim()

0

In [23]:
int_zerodim = torch.tensor(4, dtype = torch.int)
print(int_zerodim)

tensor(4, dtype=torch.int32)


In [25]:
int_zerodim.dim()

0