In [1]:
import torch

In [2]:
a = torch.ones(3, 2)
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [3]:
b = torch.ones(3, 2)
print(b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [4]:
print(a+b)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [5]:
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [6]:
a.add_(b)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [7]:
print(a)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [8]:
a.sub_(b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [9]:
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [10]:
a.mul_(b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [11]:
a.div_(b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [13]:
a.exp_()

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183],
        [2.7183, 2.7183]])

In [16]:
a = torch.ones(3, 2)
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [15]:
a.exponential_()

tensor([[0.5037, 0.2913],
        [1.1523, 1.9986],
        [2.0278, 0.0724]])

In [18]:
a.cos_()

tensor([[0.5403, 0.5403],
        [0.5403, 0.5403],
        [0.5403, 0.5403]])

In [21]:
a.bernoulli_()

tensor([[1., 0.],
        [0., 1.],
        [1., 0.]])

In [24]:
a.uniform_()

tensor([[0.0369, 0.8579],
        [0.1308, 0.3838],
        [0.6529, 0.4244]])

tensor([[1., 0.],
        [0., 1.],
        [1., 0.]])