# Mathematical and Statistical operations

In [2]:
import torch

In [3]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])
print(x)

tensor([1., 2., 3., 4., 5.])


In [4]:
torch.mean(x)

tensor(3.)

In [5]:
torch.median(x)

tensor(3.)

In [6]:
torch.std(x)

tensor(1.5811)

In [7]:
torch.var(x)

tensor(2.5000)

In [8]:
a = torch.tensor([1,2,3,4,5])
b = torch.tensor([6,7,8,9,10])
print(a)

tensor([1, 2, 3, 4, 5])


In [9]:
print(b)

tensor([ 6,  7,  8,  9, 10])


In [10]:
print(a+b)

tensor([ 7,  9, 11, 13, 15])


In [11]:
print(a-b)

tensor([-5, -5, -5, -5, -5])


In [12]:
print(b-a)

tensor([5, 5, 5, 5, 5])


In [13]:
print(a*b)

tensor([ 6, 14, 24, 36, 50])


In [22]:
x = torch.tensor([1,2,3,4,5])
y = torch.tensor([6,7,8,9,10])
print(x)

tensor([1, 2, 3, 4, 5])


In [15]:
print(y)

tensor([ 6,  7,  8,  9, 10])


In [16]:
x.add_(y)

tensor([ 7,  9, 11, 13, 15])

In [19]:
print(x)

tensor([1, 2, 3, 4, 5])


In [20]:
x.sub_(y)

tensor([-5, -5, -5, -5, -5])

In [21]:
print(x)

tensor([-5, -5, -5, -5, -5])


In [23]:
x.mul_(y)

tensor([ 6, 14, 24, 36, 50])

In [24]:
a = torch.eye(5)
print(a)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [25]:
x = torch.tensor([1,2,3,4,5])
print(x)

tensor([1, 2, 3, 4, 5])


In [26]:
torch.numel(x)

5

In [27]:
a = torch.Tensor(2,2).uniform_(0,1)
print(a)

tensor([[0.8119, 0.0424],
        [0.9911, 0.8304]])


In [28]:
b = torch.Tensor(2,2).bernoulli_()
print(b)

tensor([[0., 1.],
        [1., 1.]])


In [29]:
x = torch.Tensor(5,5).normal_()
print(x)

tensor([[ 0.1956, -1.7480,  0.7670,  1.1468,  0.1806],
        [-0.7604,  1.5444,  0.4800, -0.3745,  1.5081],
        [ 0.0310, -0.8880, -0.1724,  0.5850, -0.4956],
        [ 0.8496, -0.7742, -0.9347,  1.4333, -0.3108],
        [-0.7582,  0.3414, -0.0499,  0.0502,  0.6349]])


In [31]:
z = torch.Tensor(5,5).multinomial(10, replacement=True)
print(z)

tensor([[4, 4, 3, 0, 4, 1, 3, 4, 1, 0],
        [1, 2, 3, 0, 4, 0, 0, 2, 4, 1],
        [3, 4, 3, 0, 0, 4, 4, 0, 0, 3],
        [1, 4, 1, 1, 0, 3, 0, 4, 1, 1],
        [0, 2, 0, 1, 0, 0, 0, 3, 2, 1]])
