In [1]:
import csv
import torch
import numpy as np

In [2]:
data_path = "C:\\Users\\amirs\\Downloads\\data\\winedata.csv"

In [3]:
data_numpy = np.loadtxt(data_path, dtype = np.float32, delimiter= ';', skiprows=1)

In [4]:
print(data_numpy)

[[ 7.    0.27  0.36 ...  0.45  8.8   6.  ]
 [ 6.3   0.3   0.34 ...  0.49  9.5   6.  ]
 [ 8.1   0.28  0.4  ...  0.44 10.1   6.  ]
 ...
 [ 6.5   0.24  0.19 ...  0.46  9.4   6.  ]
 [ 5.5   0.29  0.3  ...  0.38 12.8   7.  ]
 [ 6.    0.21  0.38 ...  0.32 11.8   6.  ]]


In [5]:
type(data_numpy)

numpy.ndarray

In [6]:
data_tensor = torch.from_numpy(data_numpy)

In [7]:
print(data_tensor)

tensor([[ 7.0000,  0.2700,  0.3600,  ...,  0.4500,  8.8000,  6.0000],
        [ 6.3000,  0.3000,  0.3400,  ...,  0.4900,  9.5000,  6.0000],
        [ 8.1000,  0.2800,  0.4000,  ...,  0.4400, 10.1000,  6.0000],
        ...,
        [ 6.5000,  0.2400,  0.1900,  ...,  0.4600,  9.4000,  6.0000],
        [ 5.5000,  0.2900,  0.3000,  ...,  0.3800, 12.8000,  7.0000],
        [ 6.0000,  0.2100,  0.3800,  ...,  0.3200, 11.8000,  6.0000]])


In [8]:
type(data_tensor)

torch.Tensor

In [9]:
data_mean = torch.mean(data_tensor, dim=0)

In [10]:
print(data_mean)

tensor([6.8548e+00, 2.7824e-01, 3.3419e-01, 6.3914e+00, 4.5772e-02, 3.5308e+01,
        1.3836e+02, 9.9403e-01, 3.1883e+00, 4.8985e-01, 1.0514e+01, 5.8779e+00])


In [11]:
data_var = torch.var(data_tensor, dim=0)

In [12]:
print(data_var)

tensor([7.1211e-01, 1.0160e-02, 1.4646e-02, 2.5726e+01, 4.7733e-04, 2.8924e+02,
        1.8061e+03, 8.9455e-06, 2.2801e-02, 1.3025e-02, 1.5144e+00, 7.8436e-01])


In [13]:
print(data_tensor)

tensor([[ 7.0000,  0.2700,  0.3600,  ...,  0.4500,  8.8000,  6.0000],
        [ 6.3000,  0.3000,  0.3400,  ...,  0.4900,  9.5000,  6.0000],
        [ 8.1000,  0.2800,  0.4000,  ...,  0.4400, 10.1000,  6.0000],
        ...,
        [ 6.5000,  0.2400,  0.1900,  ...,  0.4600,  9.4000,  6.0000],
        [ 5.5000,  0.2900,  0.3000,  ...,  0.3800, 12.8000,  7.0000],
        [ 6.0000,  0.2100,  0.3800,  ...,  0.3200, 11.8000,  6.0000]])


In [14]:
data_normalised = (data_tensor - data_mean)/torch.sqrt(data_var)

In [15]:
print(data_normalised)

tensor([[ 1.7209e-01, -8.1764e-02,  2.1325e-01,  ..., -3.4914e-01,
         -1.3930e+00,  1.3786e-01],
        [-6.5743e-01,  2.1587e-01,  4.7991e-02,  ...,  1.3467e-03,
         -8.2418e-01,  1.3786e-01],
        [ 1.4756e+00,  1.7448e-02,  5.4378e-01,  ..., -4.3677e-01,
         -3.3662e-01,  1.3786e-01],
        ...,
        [-4.2042e-01, -3.7940e-01, -1.1915e+00,  ..., -2.6152e-01,
         -9.0544e-01,  1.3786e-01],
        [-1.6054e+00,  1.1666e-01, -2.8253e-01,  ..., -9.6250e-01,
          1.8574e+00,  1.2670e+00],
        [-1.0129e+00, -6.7703e-01,  3.7852e-01,  ..., -1.4882e+00,
          1.0448e+00,  1.3786e-01]])
