# One Dimension Tensor PyTorch

In [2]:
import torch

In [3]:
a = torch.tensor([1,2,3,4,5])
print(a)

tensor([1, 2, 3, 4, 5])


In [4]:
a.type()

'torch.LongTensor'

In [6]:
a.size()

torch.Size([5])

In [7]:
a[0]

tensor(1)

In [8]:
a[4]

tensor(5)

In [9]:
a.dtype

torch.int64

In [10]:
b = torch.tensor([0.0, 1.0, 2.0,3.0,4.0,5.0])
print(b)

tensor([0., 1., 2., 3., 4., 5.])


In [11]:
b.dtype

torch.float32

In [12]:
b.size()

torch.Size([6])

In [17]:
x = torch.tensor([0.0, 1.0, 2.0])
print(x)

tensor([0., 1., 2.])


In [18]:
x.dtype

torch.float32

In [19]:
a = torch.FloatTensor([1,2,3,4,5])
print(a)

tensor([1., 2., 3., 4., 5.])


In [20]:
a.dtype

torch.float32

In [21]:
x = torch.tensor([1,2,3,4,5])
print(x)

tensor([1, 2, 3, 4, 5])


In [22]:
x.dtype

torch.int64

In [23]:
x = x.type(torch.FloatTensor)
print(x)

tensor([1., 2., 3., 4., 5.])


In [24]:
x.dtype

torch.float32

In [28]:
a = torch.tensor([1,2,3,4,5,6])
print(a)

tensor([1, 2, 3, 4, 5, 6])


In [29]:
a.ndim

1

In [30]:
a_2d = a.view(2,3)
print(a_2d)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [31]:
a_2d.ndim

2

In [32]:
import numpy as np

In [33]:
numpy_array = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
print(numpy_array)

[1. 2. 3. 4. 5.]


In [38]:
type(numpy_array)

numpy.ndarray

In [39]:
torch_tensor = torch.from_numpy(numpy_array)
print(torch_tensor)

tensor([1., 2., 3., 4., 5.], dtype=torch.float64)


In [40]:
import pandas as pd

In [41]:
pandas_series = pd.Series([1,2,3,4,5,6])
print(pandas_series)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [43]:
pandas_to_torch = torch.from_numpy(pandas_series.values)

In [44]:
print(pandas_to_torch)

tensor([1, 2, 3, 4, 5, 6])


In [45]:
pandas_to_torch.dtype

torch.int64

In [46]:
a = torch.tensor([1,2,3,4,5,6])
print(a)

tensor([1, 2, 3, 4, 5, 6])


In [47]:
torch_to_list = a.tolist()

In [48]:
print(torch_to_list)

[1, 2, 3, 4, 5, 6]


In [49]:
x = torch.tensor([1,2,3,4,5])
print(x)

tensor([1, 2, 3, 4, 5])


In [50]:
x[0].item()

1

In [51]:
x[4].item()

5