# One Hot Encoding

In [1]:
import numpy as np
import torch
import csv

In [3]:
wine_path = "C:\\Users\\amirs\\Downloads\\data\\winedata.csv"

In [9]:
wine_numpy = np.loadtxt(wine_path, dtype = np.float32, delimiter=";", skiprows=1)

In [10]:
print(wine_nmpy)

[[ 7.    0.27  0.36 ...  0.45  8.8   6.  ]
 [ 6.3   0.3   0.34 ...  0.49  9.5   6.  ]
 [ 8.1   0.28  0.4  ...  0.44 10.1   6.  ]
 ...
 [ 6.5   0.24  0.19 ...  0.46  9.4   6.  ]
 [ 5.5   0.29  0.3  ...  0.38 12.8   7.  ]
 [ 6.    0.21  0.38 ...  0.32 11.8   6.  ]]


In [11]:
type(wine_numpy)

numpy.ndarray

In [14]:
wine_tensor = torch.from_numpy(wine_numpy)

In [15]:
print(wine_tensor)

tensor([[ 7.0000,  0.2700,  0.3600,  ...,  0.4500,  8.8000,  6.0000],
        [ 6.3000,  0.3000,  0.3400,  ...,  0.4900,  9.5000,  6.0000],
        [ 8.1000,  0.2800,  0.4000,  ...,  0.4400, 10.1000,  6.0000],
        ...,
        [ 6.5000,  0.2400,  0.1900,  ...,  0.4600,  9.4000,  6.0000],
        [ 5.5000,  0.2900,  0.3000,  ...,  0.3800, 12.8000,  7.0000],
        [ 6.0000,  0.2100,  0.3800,  ...,  0.3200, 11.8000,  6.0000]])


In [16]:
type(wine_tensor)

torch.Tensor

In [17]:
data = wine_tensor[:, :-1]

In [18]:
print(data)

tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
        [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
        [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
        ...,
        [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
        [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
        [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]])


In [27]:
target = wine_tensor[:, -1].long()

In [28]:
print(target)

tensor([6, 6, 6,  ..., 6, 7, 6])


In [29]:
target.shape

torch.Size([4898])

In [30]:
target.shape[0]

4898

In [31]:
target.unique()

tensor([3, 4, 5, 6, 7, 8, 9])

In [32]:
target_onehot = torch.zeros(target.shape[0], 10)

In [33]:
print(target_onehot)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])


In [34]:
result = target_onehot.scatter_(1, target.unsqueeze(1), 1.0)

In [35]:
print(result)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
