# Operations in PyTorch

In [1]:
import torch

In [2]:
a = torch.ones(10,2, dtype= torch.double)
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)


In [3]:
type(a)

torch.Tensor

In [4]:
a.dtype

torch.float64

In [5]:
b = torch.tensor([[1,2], [3,4]], dtype= torch.short)
print(b)

tensor([[1, 2],
        [3, 4]], dtype=torch.int16)


In [6]:
b.dtype

torch.int16

In [7]:
x = torch.zeros(10,3).double()
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [8]:
x.dtype

torch.float64

In [9]:
x = torch.zeros(10,3).short()
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)


In [11]:
x = torch.zeros(10, 2).to(torch.double)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)


In [12]:
x = torch.zeros(10, 2).to(torch.short)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int16)


In [13]:
a = torch.ones(3,2)
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [16]:
a.shape

torch.Size([3, 2])

In [17]:
a_tr = torch.transpose(a,0,1)
print(a_tr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [18]:
a_tr.shape

torch.Size([2, 3])

In [19]:
x = torch.tensor([[4.0, 5.0], [1.0, 3.0], [8.0, 9.0]])
print(x)

tensor([[4., 5.],
        [1., 3.],
        [8., 9.]])


In [20]:
x.shape

torch.Size([3, 2])

In [22]:
x.storage()

 4.0
 5.0
 1.0
 3.0
 8.0
 9.0
[torch.FloatStorage of size 6]

In [24]:
b = x.storage()

In [25]:
b[0]

4.0

In [26]:
b[2]

1.0

In [27]:
a = torch.tensor([[1,2,3], [4,5,6]])
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [28]:
a[0]

tensor([1, 2, 3])

In [29]:
a[1]

tensor([4, 5, 6])

In [30]:
a[0][1]

tensor(2)

In [31]:
a[1][1]

tensor(5)

In [32]:
a[1][1] = 500

In [33]:
print(a)

tensor([[  1,   2,   3],
        [  4, 500,   6]])


In [35]:
x= torch.tensor([[1.0, 2.0], [3.0, 4.0]], requires_grad= True)
print(x)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [36]:
b = torch.zeros(3,3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [38]:
b.fill_diagonal_(100)

tensor([[100.,   0.,   0.],
        [  0., 100.,   0.],
        [  0.,   0., 100.]])

In [39]:
x = torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


In [40]:
x.repeat(4,2)

tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])

In [41]:
x.repeat(4,4)

tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]])