# PyTorch

- Two dimension tensor
- Basic operations
- Indexing and slicing

In [3]:
import torch

In [4]:
a = [[1,2,3], [4,5,6], [7,8,9]]

In [5]:
b = torch.tensor(a)

In [6]:
print(b)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [8]:
b.ndim

2

In [9]:
b.shape

torch.Size([3, 3])

In [11]:
b.size()

torch.Size([3, 3])

In [12]:
b.numel()

9

In [14]:
# Indexing and slicing
print(b)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [15]:
b[0]

tensor([1, 2, 3])

In [16]:
b[2]

tensor([7, 8, 9])

In [18]:
b[1:3, 2]

tensor([6, 9])

In [19]:
# Basic operations

In [20]:
a = torch.tensor([[1,0], [0,1]])
print(a)

tensor([[1, 0],
        [0, 1]])


In [21]:
b = torch.tensor([[2,1], [1,2]])
print(b)

tensor([[2, 1],
        [1, 2]])


In [22]:
z = a + b
print(z)

tensor([[3, 1],
        [1, 3]])


In [23]:
x = torch.tensor([[2,1], [1,2]])
print(x)

tensor([[2, 1],
        [1, 2]])


In [24]:
z = 3 * x
print(z)

tensor([[6, 3],
        [3, 6]])
