# Storage

In [2]:
import torch

In [3]:
a = torch.tensor([[1.0, 2.0], [4.0, 5.0], [7.0, 8.0]])
print(a)

tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])


In [5]:
a.size()

torch.Size([3, 2])

In [6]:
a.dim()

2

In [9]:
a.storage()

 1.0
 2.0
 4.0
 5.0
 7.0
 8.0
[torch.FloatStorage of size 6]

In [10]:
a_storage = a.storage()
print(a_storage)

 1.0
 2.0
 4.0
 5.0
 7.0
 8.0
[torch.FloatStorage of size 6]


In [11]:
a_storage[0]

1.0

In [12]:
a_storage[1]

2.0

In [13]:
a_storage[3]

5.0

In [14]:
print(a)

tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])


In [15]:
a_storage[0] = 50.0

In [16]:
print(a)

tensor([[50.,  2.],
        [ 4.,  5.],
        [ 7.,  8.]])
