# Tensor Metadata : Size, offset and stride

In [1]:
import torch

In [2]:
x = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
print(x)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [4]:
x.storage()

 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
[torch.FloatStorage of size 6]

In [5]:
s = x.storage()

In [6]:
type(s)

torch.FloatStorage

In [7]:
s.dtype

torch.float32

# Stride

In [9]:
x.stride()

(2, 1)

In [11]:
x.size()

torch.Size([3, 2])

In [12]:
p = torch.tensor([[4.0, 1.0], [5.0,3.0], [10.0, 1.0]])
print(p)

tensor([[ 4.,  1.],
        [ 5.,  3.],
        [10.,  1.]])


In [13]:
p[0]

tensor([4., 1.])

In [14]:
p[1]

tensor([5., 3.])

In [16]:
p[2]

tensor([10.,  1.])

In [17]:
p[0][0]

tensor(4.)

In [18]:
p[0][1]

tensor(1.)

In [23]:
p_offset = p[1][1]

In [24]:
p_offset.storage_offset()

3

In [22]:
p[1][1]

tensor(3.)