# Pytorch Tensors

In [1]:
import torch

In [2]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [3]:
a[0]

tensor(1.)

In [4]:
a[4]

tensor(1.)

In [5]:
a[10]

IndexError: index 10 is out of bounds for dimension 0 with size 5

In [6]:
a[0:3]

tensor([1., 1., 1.])

In [8]:
a[1]

tensor(1.)

In [9]:
print(float(a[1]))

1.0


In [10]:
print(a)

tensor([1., 1., 1., 1., 1.])


In [11]:
a[0]= 5.0

In [12]:
print(a)

tensor([5., 1., 1., 1., 1.])


In [13]:
b = torch.zeros(5)
print(b)

tensor([0., 0., 0., 0., 0.])


In [14]:
b[0]

tensor(0.)

In [15]:
b[1:3]

tensor([0., 0.])

In [16]:
b[1]= 10.0

In [17]:
print(b)

tensor([ 0., 10.,  0.,  0.,  0.])


In [19]:
x= torch.empty(5, 3)
print(x)

tensor([[1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38]])


In [20]:
y = torch.rand(5,5)

In [21]:
print(y)

tensor([[0.7823, 0.8858, 0.0131, 0.2460, 0.6308],
        [0.8705, 0.3650, 0.1885, 0.6739, 0.2912],
        [0.4149, 0.7526, 0.1714, 0.6241, 0.4777],
        [0.2786, 0.3322, 0.5168, 0.7746, 0.2648],
        [0.7201, 0.7054, 0.6670, 0.3975, 0.7985]])


In [23]:
x = torch.ones(5,5, dtype= torch.int32)
print(x)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)


In [24]:
x= torch.tensor([5.5, 15.5])
print(x)

tensor([ 5.5000, 15.5000])


In [25]:
y = x.new_ones(5,3, dtype = torch.double)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [26]:
a = torch.tensor([1.0, 2.0, 3.0, 4.0])
print(a)

tensor([1., 2., 3., 4.])


In [27]:
print(a.size())

torch.Size([4])


In [31]:
# 2D tensor
a = torch.tensor([[5.0, 6.0], [8.0, 9.0], [11.0, 12.0]])
print(a)

tensor([[ 5.,  6.],
        [ 8.,  9.],
        [11., 12.]])


In [32]:
a.shape

torch.Size([3, 2])

In [34]:
print(a.size())

torch.Size([3, 2])
