# Transpose

In [1]:
import torch

In [2]:
x = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0,6.0]])
print(x)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [3]:
x.size()

torch.Size([3, 2])

In [4]:
x.dim()

2

In [5]:
x_t = x.t()
print(x_t)

tensor([[1., 3., 5.],
        [2., 4., 6.]])


In [6]:
x_t.size()

torch.Size([2, 3])

In [7]:
id(x.storage()) == id(x_t.storage())

True

In [8]:
a = torch.ones(3,4,5)
print(a)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


In [11]:
a.size()

torch.Size([3, 4, 5])

In [12]:
a.dim()

3

In [9]:
transpose_a = a.transpose(0,1)
print(transpose_a)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


In [13]:
transpose_a.size()

torch.Size([4, 3, 5])

In [14]:
transpose_a.dim()

3