# Type Casting
* Convert data from one type to another

In [1]:
import torch

In [2]:
double_type = torch.ones(5,2, dtype= torch.double)

In [3]:
print(double_type)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)


In [7]:
short_type = torch.tensor([[1,2], [3,4], [5,6]], dtype= torch.short)
print(short_type)

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int16)


In [9]:
double_t = torch.zeros(10,2, dtype= torch.double)

In [10]:
print(double_t)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)


In [11]:
double_t = torch.zeros(5,2).to(torch.double)
print(double_t)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)


In [12]:
double_t = torch.zeros(5,2).double()
print(double_t)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)


In [13]:
short_t = torch.zeros(2,3).short()
print(short_t)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)


In [14]:
short_t = torch.zeros(4,4).to(dtype= torch.short)
print(short_t)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int16)
